-- 現金出納帳→MoneyForward仕訳帳CSV変換用マスタテーブル

-- 仕訳ルール（Pythonのif/elifを1行1ルール化）
CREATE TABLE IF NOT EXISTS m_mf_journal_rule (
    id                           SERIAL PRIMARY KEY,
    description_c                VARCHAR(50)  NOT NULL,
    description_d_keyword        VARCHAR(100),
    priority                     INTEGER      NOT NULL DEFAULT 100,
    amount_source                VARCHAR(10)  NOT NULL,
    debit_account                VARCHAR(50)  NOT NULL,
    debit_sub_account            VARCHAR(100) DEFAULT '',
    debit_department             VARCHAR(50)  DEFAULT '',
    debit_tax_resolver           VARCHAR(30)  NOT NULL,
    credit_account               VARCHAR(50)  NOT NULL,
    credit_sub_account           VARCHAR(100) DEFAULT '',
    credit_sub_account_template  VARCHAR(200) DEFAULT '',
    credit_department            VARCHAR(50)  DEFAULT '',
    credit_tax_resolver          VARCHAR(30)  NOT NULL,
    summary_template             VARCHAR(200) NOT NULL DEFAULT '{d}',
    requires_client_mapping      BOOLEAN      NOT NULL DEFAULT FALSE,
    del_flg                      VARCHAR(1)   NOT NULL DEFAULT '0',
    add_date_time                TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    add_user_no                  INTEGER,
    modify_date_time             TIMESTAMP,
    modify_user_no               INTEGER
);
CREATE INDEX IF NOT EXISTS idx_mf_journal_rule_descc ON m_mf_journal_rule(description_c, priority);

-- 得意先マッピング（経理Excel表記→MF正式名）
CREATE TABLE IF NOT EXISTS m_mf_client_mapping (
    id               SERIAL PRIMARY KEY,
    alias            VARCHAR(200) NOT NULL,
    mf_client_name   VARCHAR(200) NOT NULL,
    del_flg          VARCHAR(1)   NOT NULL DEFAULT '0',
    add_date_time    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    add_user_no      INTEGER,
    modify_date_time TIMESTAMP,
    modify_user_no   INTEGER
);
CREATE INDEX IF NOT EXISTS idx_mf_client_mapping_alias ON m_mf_client_mapping(alias) WHERE del_flg = '0';

-- シード: 仕訳ルール（19件、priority小=高優先度）
INSERT INTO m_mf_journal_rule (description_c, description_d_keyword, priority, amount_source,
    debit_account, debit_sub_account, debit_department, debit_tax_resolver,
    credit_account, credit_sub_account, credit_sub_account_template, credit_department, credit_tax_resolver,
    summary_template, requires_client_mapping)
VALUES
    ('ｺﾞﾐ袋未収金',  NULL,                    100, 'INCOME',  '現金', '', '', 'OUTSIDE',                '未収入金', '', 'ゴミ袋／{client}', '', 'OUTSIDE', '{d}', TRUE),
    ('ゴミ袋未収金',  NULL,                    100, 'INCOME',  '現金', '', '', 'OUTSIDE',                '未収入金', '', 'ゴミ袋／{client}', '', 'OUTSIDE', '{d}', TRUE),
    ('売掛金',      '㊤',                     10,  'INCOME',  '現金', '', '', 'OUTSIDE',                '売掛金',   'その他', '',       '', 'OUTSIDE', '{d}', FALSE),
    ('売掛金',       NULL,                    100, 'INCOME',  '現金', '', '', 'OUTSIDE',                '売掛金',   '', '{client}',     '', 'OUTSIDE', '{d}', TRUE),
    ('売上',         NULL,                    100, 'INCOME',  '現金', '', '', 'OUTSIDE',                '売上高',   '物販売上高', '', '物販事業部', 'SALES_AUTO', '{d}', FALSE),
    ('雑収入',      '五光産業',                10,  'INCOME',  '現金', '', '', 'OUTSIDE',                '雑収入',   '段ボール処分', '', '', 'SALES_10', '{d}', FALSE),
    ('雑収入',       NULL,                    100, 'INCOME',  '現金', '', '', 'OUTSIDE',                '雑収入',   '', '',             '', 'SALES_10', '{d}', FALSE),
    ('普通預金',     NULL,                    100, 'PAYMENT', '現金', '小口現金', '', 'OUTSIDE',        '現金',     '', '',             '', 'OUTSIDE', '現金→普通預金入金　預金袋', FALSE),
    ('仕入',         NULL,                    100, 'PAYMENT', '仕入高', '', '物販事業部', 'PURCHASE_AUTO', '現金',  '', '',            '', 'OUTSIDE', '{d}', FALSE),
    ('旅費交通費',   NULL,                    100, 'PAYMENT', '旅費交通費', '', '物販事業部', 'PURCHASE_10_TRAVEL', '現金', '', '',    '', 'OUTSIDE', '{d}', FALSE),
    ('通信費',       NULL,                    100, 'PAYMENT', '通信費', '', '物販事業部', 'PURCHASE_10',  '現金',   '', '',            '', 'OUTSIDE', '{d}', FALSE),
    ('運賃',         NULL,                    100, 'PAYMENT', '荷造運賃', '', '物販事業部', 'PURCHASE_10', '現金',  '', '',            '', 'OUTSIDE', '{d}', FALSE),
    ('雑費',        '大竹市ﾘｻｲｸﾙｾﾝﾀｰ',         10,  'PAYMENT', '雑費', '', '物販事業部', 'OUTSIDE_PURCHASE_FULL', '現金', '', '',      '', 'OUTSIDE', '{d}', FALSE),
    ('雑費',         NULL,                    100, 'PAYMENT', '消耗品費', '', '物販事業部', 'PURCHASE_AUTO_WIDE', '現金', '', '',      '', 'OUTSIDE', '{d}', FALSE),
    ('租税公課',    '法務局',                  10,  'PAYMENT', '租税公課', '印紙税', '物販事業部', 'OUTSIDE', '現金', '', '',           '', 'OUTSIDE', '{d} 印紙税', FALSE),
    ('租税公課',    '宮島松大汽船',             11,  'PAYMENT', '租税公課', '', '物販事業部', 'OUTSIDE_PURCHASE_SHORT', '現金', '', '', '', 'OUTSIDE', '入島税 {d}', FALSE),
    ('租税公課',     NULL,                    100, 'PAYMENT', '租税公課', '', '', 'OUTSIDE',               '現金',  '', '',            '', 'OUTSIDE', '{d}', FALSE),
    ('福利厚生費',   NULL,                    100, 'PAYMENT', '福利厚生費', '', '物販事業部', 'PURCHASE_AUTO_WIDE', '現金', '', '',     '', 'OUTSIDE', '{d}', FALSE);

-- シード: 得意先マッピング（client_mapping.json から70件）
INSERT INTO m_mf_client_mapping (alias, mf_client_name) VALUES
('錦 病院', '(岩国) 医療法人　錦病院'),
('割烹 宇恵喜', '割烹  宇恵喜'),
('畑田 和彦', '畑田 和彦'),
('元町四丁目自治会', '元町四丁目 自治会'),
('上様', 'その他'),
('上 様', 'その他'),
('大竹市役所三倉岳県立自然公園協議会', 'その他'),
('㈱ ぬまご', '（株） ぬまご'),
('㈱ カキダ', '株式会社 カキダ'),
('五日市 あかり園', '五日市 あかり園'),
('五日市 ｸﾞﾘｰﾝﾋﾙﾎｰﾑ', '五日市グリーンヒルホーム'),
('ﾘﾋﾞﾝｸﾞｼｮｯﾌﾟ なかむら', 'リビングショップなかむら'),
('藤本商店', '藤本商店'),
('木野川紙業㈱', '木野川紙業広島本店'),
('㈱ 釘本文理堂', '（株）釘本文理堂'),
('サンフローマン', 'サンフローマン'),
('山崎商会', '山崎商会'),
('まるや', 'まるや'),
('くば漁業協同組合', 'くば漁業協同組合'),
('大竹郷心会', '大竹郷心会'),
('㈱山陽精機', '（株）山陽精機'),
('大伸堂製菓店', '大伸堂製菓店'),
('倉田鮮魚店', '倉田鮮魚店'),
('沖中鮮魚店', '沖中鮮魚店'),
('詩仙堂', '詩仙堂'),
('木村愛犬病院', '木村愛犬病院'),
('伊崎商店', '伊崎商店'),
('仁天堂薬局', '仁天堂薬局'),
('坪根文具店', '坪根文具店'),
('㈱紀陽', '（株）紀陽'),
('うお助', '（有）うお助'),
('㈲ うお助', '（有）うお助'),
('日本果実工業㈱', '日本果実工業（株）久賀工場'),
('㈱栄宏鋼材', '（株）栄宏鋼材'),
('有限会社 三友', '（有）三友'),
('㈲ 三友', '（有）三友'),
('大竹市ｼﾙﾊﾞｰ人材ｾﾝﾀｰ', '（公）大竹市シルバー人材センター'),
('㈲大竹市民葬祭', '(有)大竹市民葬祭'),
('大竹市民葬祭', '(有)大竹市民葬祭'),
('大竹葬儀社', '㈲ 大竹葬儀社'),
('原田食料品店', '(三ツ石) 原田食料品店'),
('宗教法人 清和ﾋﾞﾙ', '宗教法人　清和ビル'),
('みたらい商店', 'みたらい商店'),
('横田商店', '(岩国) 横田商店'),
('㈱ 幸房 ハウスみいり', '株式会社幸房 ハウスみいり'),
('株式会社 竹内', '（株）竹内'),
('株式会社竹内', '（株）竹内'),
('㈲さかもと家電', '(有)さかもと家電'),
('㈱コメリ パワー大竹店', '(株)コメリパワー大竹店'),
('㈲河内商店', '（有）河内商店'),
('㈱幸房 ひよこの家', '㈱ 幸房 ひよこの家'),
('㈱ 幸房 ひよこの家', '㈱ 幸房 ひよこの家'),
('㈱モリタ 広島営業所', '（株）モリタ 広島営業所'),
('木村商店', '(南栄) 木村商店'),
('木村 商店', '(南栄) 木村商店'),
('セブンイレブン 大竹立戸店', 'セブンイレブン大竹立戸'),
('ｾﾌﾞﾝｲﾚﾌﾞﾝ大竹立戸店', 'セブンイレブン大竹立戸'),
('セブンイレブン 大竹本町店', 'セブンイレブン大竹本町'),
('ｾﾌﾞﾝｲﾚﾌﾞﾝ大竹本町店', 'セブンイレブン大竹本町'),
('ｾﾌﾞﾝｲﾚﾌﾞﾝ大竹本町', 'セブンイレブン大竹本町'),
('セブンイレブン 大竹西栄店', 'セブンイレブン大竹西栄'),
('ｾﾌﾞﾝｲﾚﾌﾞﾝ大竹西栄店', 'セブンイレブン大竹西栄'),
('セブンイレブン 大竹御園店', 'セブンイレブン大竹御園'),
('ｾﾌﾞﾝｲﾚﾌﾞﾝ大竹御園店', 'セブンイレブン大竹御園'),
('ｾﾌﾞﾝｲﾚﾌﾞﾝ大竹御園', 'セブンイレブン大竹御園'),
('セブンイレブン 大竹ｲﾝﾀｰ店', 'セブンイレブン大竹インター'),
('ｾﾌﾞﾝｲﾚﾌﾞﾝ大竹ｲﾝﾀｰ店', 'セブンイレブン大竹インター'),
('池本食品', '池本食品'),
('五光産業㈱', '五光産業(株)'),
('光 商事 ㈱', '光商事（株）'),
('大久食料品店', '大久食料品店'),
('㈲手洗環境衛生', '（有）手洗環境衛生');
