package jp.co.oda32.domain.repository.purchase;

import jp.co.oda32.domain.model.purchase.MPurchasePriceChangePlan;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;

import java.time.LocalDate;
import java.util.List;

/**
 * 仕入価格変更予定マスタ(m_purchase_price_change_plan)のリポジトリインターフェース
 *
 * @author k_oda
 * @since 2022/10/13
 */
public interface MPurchasePriceChangePlanRepository extends JpaRepository<MPurchasePriceChangePlan, Integer>, JpaSpecificationExecutor<MPurchasePriceChangePlan> {

    @Modifying
    @Query(value = "update m_purchase_price_change_plan set purchase_price_reflect = true" +
            " from m_purchase_price mpp" +
            "         join m_supplier ms on mpp.supplier_no = ms.supplier_no" +
            "         join w_sales_goods wsg on wsg.shop_no=mpp.shop_no and wsg.goods_no=mpp.goods_no" +
            " where m_purchase_price_change_plan.purchase_price_reflect = false" +
            "  and m_purchase_price_change_plan.shop_no=mpp.shop_no" +
            "  and mpp.supplier_no = ms.supplier_no" +
            "  and m_purchase_price_change_plan.goods_code=wsg.goods_code" +
            "  and mpp.goods_price=m_purchase_price_change_plan.after_price" +
            "  and m_purchase_price_change_plan.change_plan_date <= current_date;", nativeQuery = true)
    int updateReflectComplete();

    List<MPurchasePriceChangePlan> findByPurchasePriceReflectFalse();

    void deleteByShopNoAndGoodsCodeAndChangePlanDate(Integer shopNo, String goodsCode, LocalDate changePlanDate);

    /**
     * 自動生成され「作成」ステータスのままの見積に対応する仕入価格変更予定の
     * 作成済みフラグをリセットする（バッチ再実行時に上書き処理するため）
     * <p>
     * 対象: m_purchase_price_change_plan が partner_price_change_plan_created=true、
     * かつ未反映(purchase_price_reflect=false)、かつ auto_generated=true &amp; status='00'
     * の t_estimate に (shop_no, change_plan_date=price_change_date, goods_code) が一致するもの。
     */
    @Modifying
    @Query(value = "UPDATE m_purchase_price_change_plan pcp" +
            " SET partner_price_change_plan_created = false" +
            " WHERE pcp.del_flg = '0'" +
            "   AND pcp.partner_price_change_plan_created = true" +
            "   AND pcp.purchase_price_reflect = false" +
            "   AND EXISTS (" +
            "     SELECT 1 FROM t_estimate e" +
            "     JOIN t_estimate_detail ed ON e.estimate_no = ed.estimate_no" +
            "     WHERE e.shop_no = pcp.shop_no" +
            "       AND e.auto_generated = true" +
            "       AND e.estimate_status = '00'" +
            "       AND e.del_flg = '0'" +
            "       AND e.price_change_date = pcp.change_plan_date" +
            "       AND ed.goods_code = pcp.goods_code" +
            "       AND ed.del_flg = '0'" +
            "   )", nativeQuery = true)
    int resetCreatedFlagForAutoGeneratedCreateEstimate();
}
