package jp.co.oda32.domain.model.bcart;

import lombok.Getter;
import lombok.Setter;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;

@Entity
@Getter
@Setter
@Table(name = "t_smile_order_import_file")
public class TSmileOrderImportFile {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "slip_date")
    private LocalDate slipDate;

    @Column(name = "slip_number")
    private Integer slipNumber;

    @Column(name = "processing_serial_number")
    private Long processingSerialNumber;

    @Column(name = "detail_type")
    private Integer detailType;

    @Column(name = "line_number")
    private Integer lineNumber;

    @Column(name = "customer_code")
    private String customerCode;

    @Column(name = "customer_comp_name")
    private String customerCompName;

    @Column(name = "customer_comp_name_2")
    private String customerCompName2;

    @Column(name = "delivery_code")
    private String deliveryCode;

    @Column(name = "delivery_comp_name")
    private String deliveryCompName;

    @Column(name = "person_in_charge_code")
    private String personInChargeCode;

    @Column(name = "billing_type")
    private Integer billingType;

    @Column(name = "accounts_receivable_type")
    private Integer accountsReceivableType;

    @Column(name = "transaction_type")
    private Integer transactionType;

    @Column(name = "transaction_type_attribute")
    private Integer transactionTypeAttribute;

    @Column(name = "product_code")
    private String productCode;

    @Column(name = "product_name")
    private String productName;

    @Column(name = "set_quantity")
    private BigDecimal setQuantity;

    @Column(name = "order_pro_count")
    private BigDecimal orderProCount;

    @Column(name = "count_unit")
    private String countUnit;

    @Column(name = "quantity")
    private BigDecimal quantity;

    @Column(name = "quantity_unit")
    private String quantityUnit;

    @Column(name = "unit_price")
    private BigDecimal unitPrice;

    @Column(name = "amount")
    private BigDecimal amount;

    @Column(name = "original_unit_price")
    private BigDecimal originalUnitPrice;

    @Column(name = "cost_amount")
    private BigDecimal costAmount;

    @Column(name = "gross_margin")
    private BigDecimal grossMargin;

    @Column(name = "unit_price_margin")
    private BigDecimal unitPriceMargin;

    @Column(name = "tax_type")
    private Integer taxType;

    @Column(name = "tax_rate")
    private BigDecimal taxRate;

    @Column(name = "internal_consumption_tax")
    private BigDecimal internalConsumptionTax;

    @Column(name = "line_summary_code")
    private String lineSummaryCode;

    @Column(name = "line_summary_1")
    private String lineSummary1;

    @Column(name = "line_summary_2")
    private String lineSummary2;

    @Column(name = "remarks_code")
    private String remarksCode;

    @Column(name = "remarks")
    private String remarks;

    @Column(name = "order_number")
    private Integer orderNumber;

    @Column(name = "order_line")
    private Integer orderLine;

    @Column(name = "quote_processing_serial_number")
    private Integer quoteProcessingSerialNumber;

    @Column(name = "quote_line")
    private Integer quoteLine;

    @Column(name = "auto_generated_type")
    private Integer autoGeneratedType;

    @Column(name = "slip_consumption_tax_calculation_type")
    private Integer slipConsumptionTaxCalculationType;

    @Column(name = "data_occurrence_type")
    private Integer dataOccurrenceType;

    @Column(name = "counterpart_processing_serial_number")
    private Integer counterpartProcessingSerialNumber;

    @Column(name = "input_pattern_number")
    private String inputPatternNumber;

    @Column(name = "slip_serial_number")
    private String slipSerialNumber;

    @Column(name = "counterpart_slip_serial_number")
    private String counterpartSlipSerialNumber;

    @Column(name = "code_1")
    private String code1;

    @Column(name = "code_2")
    private String code2;

    @Column(name = "company_store_code")
    private String companyStoreCode;

    @Column(name = "classification_code")
    private String classificationCode;

    @Column(name = "slip_type")
    private String slipType;

    @Column(name = "trading_partner_code")
    private String tradingPartnerCode;

    @Column(name = "selling_unit_price")
    private BigDecimal sellingUnitPrice;

    @Column(name = "counterpart_product_code")
    private String counterpartProductCode;

    @Column(name = "check_mark_type")
    private Integer checkMarkType;

    @Column(name = "consumption_tax_classification")
    private Integer consumptionTaxClassification;

    @Column(name = "b_cart_order_id")
    private Long bCartOrderId;

    @Column(name = "csv_exported")
    private boolean csvExported;

    @Column(name = "b_cart_logistics_id")
    private Long bCartLogisticsId; // Bカート発送ID（出荷ID） (整数, 最大11桁)

    @Column(name = "asana_task_add")
    private boolean asanaTaskAdd;

    @Column(name = "psn_updated")
    private boolean psnUpdated;

}
